spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dengrenbocq/spring-cloud-sell-config-repo.git
#          username:
#          password:
#          设置本地仓库地址
#          basedir: /Users/admin/code/myProjects/java/imooc/SpringCloud_Sell/config/basedir
  rabbitmq:
    host: 123.206.62.172
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      expose: "*"