eureka:
  client:
    service-url:
#      可以同时注册到多台注册中心逗号分隔
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
#  eureka状态链接地址
#  instance:
#    hostname: clientName
spring:
  application:
    name: client